### ISSUE TITLE
Hydra usage feedback

### ISSUE THREAD

**Issue by omry** [felixkreuk/uncertainty#1]
Hi Felix,
glad to see you finally made some code using Hydra available.

Here is some quick feedback:

You are not using hierarchical config,
This:

```yaml
batch_size: 128
learning_rate: 0.0001
model: vgg16
dataset: cifar10
data_dir: /data/felix/datasets
val_ratio: 0.1
download: false
num_workers: 32
gpus: 4
overfit_pct: 1.0
eps_smooth: 0
semantic_dist: false
semantic_dist_temperature: 15
label_mixup: false
mixup_alpha: 0.2
```
can become:
```yaml
training:
  batch_size: 128
  learning_rate: 0.0001
  val_ratio: 0.1
  num_workers: 32
  gpus: 4
  overfit_pct: 1.0
  eps_smooth: 0
  semantic_dist: false
  semantic_dist_temperature: 15
  label_mixup: false
  mixup_alpha: 0.2

model:
  name vgg16
  download: false
  # other model specific things here, maybe architecture class name?

dataset:
  name: cifar10
  data_dir: /data/felix/datasets
  # other dataset specific things here, for example:
  mean: [0.4914, 0.4822, 0.4465]   # in json form

  std:    # or on yaml list form
    - 0.2023
    - 0.1994
    - 0.2010
  # maybe transform definitions too.
```

This will set the ground for replacing the dataset from the config later using composition:

```yaml
defaults:
  - dataset: cifar10

# everything except dataset goes here.
```

Hope this helps.
